--- #YAML:1.0
name: CGI-Application-Plugin-Forward
version: 1.03
author:
  - Michael Graham <mag-perl@occamstoothbrush.com>
abstract: Pass control from one run mode to another
license: perl
requires:
  CGI::Application: 0
  Test::More: 0
provides:
  CGI::Application::Plugin::Forward:
    file: lib/CGI/Application/Plugin/Forward.pm
    version: 1.03
generated_by: Module::Build version 0.2611
